### ISSUE TITLE
As a story submitter, I want an interactive interface showing me how to create my story

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-contribution-stories#1]
Implementation:  Have examples and/or templates for submitters to use, potentially using Javascript to show/hide them.

**Comment by shaunagm** [comment]
Also, it would be good to have a more interactive guide through the process (I'm envisioning an "add the next step" button, maybe with guided questions) which we can create via Javascript.

**Comment by shaunagm** [comment]
Closed by ef2ee1fa9fdc72c736c7d0adf6d04041df32807f and bb75d7e7578e11f77d563a62ba57750c6f0e7968.
