### ISSUE TITLE
As a site editor, I want to know that the stories are shareable under a license that permits sharing

### ISSUE THREAD

**Issue by shaunagm** [openhatch/oh-contribution-stories#14]
Implementation: Above the "Submit" button is a remark that by submitting, you agree to share this under CC Zero???

**Comment by paulproteus** [comment]
Presumably we should decide what license that should be.

**Comment by shaunagm** [comment]
Added to submit form here (3ba498b0124da4bba6298c761ac50b740ac84738) and about page here (e77cef426707526e8b7b36e294a3ac0ee8d9b2b2).  Am happy to reconsider the license I chose.
