### ISSUE TITLE
As a site visitor, I see the site has a catchy domain name so I can easily remember it & tell friends

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-contribution-stories#17]
- contributionstories.com
- ???

Note that we can ask other people for ideas, too.

**Comment by paulproteus** [comment]
We went with mergestories.com for now.

**Comment by paulproteus** [comment]
"You must commit this file to the root directory of your Pages repository in the same branch as your Pages content (master for User and Organization Pages, gh-pages for Project Pages)."

-- https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages

That is to say, we're going to have to add this to the gh-pages branch, it seems.

I'm not sure yet how to do that with the tooling we have. I guess we could add this to our deploy script. Might as well.

While we're at it:

https://github.com/davisp/ghp-import

mentions a command line parameter to create a "nojekyll" file. Thumbs up to that config parameter.

**Comment by shaunagm** [comment]
Closed by  048d4fcee8e66e734ecf25a30d4bac5c2d504adb
