### ISSUE TITLE
As a story submitter, I want to see a form that lets me submit a story

### ISSUE THREAD

**Issue by shaunagm** [openhatch/oh-contribution-stories#4]
Implementation: Make an HTML form, and make sure it gets rendered into the site by Pelican

**Comment by paulproteus** [comment]
Success criteria for this issue:

Form with HTML text area.

Other chatter:

Make sure a link appears to this, in the theme
(maybe v2, provide a nice-looking UI template, like the startup signup page thing Asheesh likes)
Shauna -- comments on http://www.smashingmagazine.com/wp-content/uploads/2011/08/vaultpress-screenshot.jpg as a sample UI?
Shauna values the idea of this being non-intimidating
Shauna values the idea of this encouraging people to get into the nitty-gritty
Asheesh thinks this is the kind of thing a very UI-oriented person could help extraordinarily with.
Shauna wants writers to be encouraged to write a fair bit, to help us tag stories (and perhaps paragraphs within stories).
<ramble>
For OSCTC attendees, we want the UI to be simple.
</ramble>
