### ISSUE TITLE
As a reader, I want to be able to visually distinguish one blog post from another

### ISSUE THREAD

**Issue by mollyclare** [openhatch/oh-contribution-stories#43]
The two columns under Feature Stories are too close to each other. It's hard to tell at a glance that they're different stories. It seems to be about 30px, and it should be (I'm estimating) closer to 60px.

**Comment by emmet0r** [comment]
Hartnell group working on this now!

**Comment by shaunagm** [comment]
Awesome.  :)   Ping me if you need help - I'm "shauna" on Freenode/#openhatch.

**Comment by emmet0r** [comment]
Rats! We got so close and ran out of time - but thanks for trying to help out over IRC!

**Comment by shaunagm** [comment]
Do you remember who was working on it?  Perhaps @katieirenec can reach out to them and we can set up a group hangout to work on it together at some point.

**Comment by emmet0r** [comment]
Yep, @AnitaGarcia819 was working with me on this one! Just sent you e-mail with a bit more info, too.

**Comment by shaunagm** [comment]
Great!  Looking forward to following up on this with all of you.  :)
